# Generated by Django 3.0.6 on 2020-09-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=30)),
                ('storage_type', models.CharField(default='MYSQL', max_length=20)),
                ('remark', models.TextField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'storage_item',
            },
        ),
    ]
