# Generated by Django 3.0.6 on 2020-06-05 16:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('action_code', models.CharField(max_length=255)),
                ('prev_menu', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_url', models.CharField(max_length=255)),
                ('p_id', models.BigIntegerField()),
                ('is_function', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('remove_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'sys_menu',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mark', models.CharField(max_length=255)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('remove_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'sys_role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('remove_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'sys_user',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('expire_time', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sys_auth.User')),
            ],
            options={
                'db_table': 'sys_token',
            },
        ),
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_auth.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_auth.User')),
            ],
            options={
                'db_table': 'sys_user_role',
            },
        ),
        migrations.CreateModel(
            name='RoleMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_auth.Menu')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_auth.Role')),
            ],
            options={
                'db_table': 'sys_role_menu',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(through='sys_auth.RoleMenu', to='sys_auth.Menu'),
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(through='sys_auth.RoleUser', to='sys_auth.User'),
        ),
    ]
