# Generated by Django 3.0.6 on 2020-06-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('tag_remark', models.CharField(max_length=255)),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(null=True)),
                ('remove_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
    ]
