# Generated by Django 3.0.6 on 2020-06-22 03:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datacenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_name', models.CharField(max_length=60)),
                ('dc_address', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=255, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('remove_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'asset_datacenter',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=60)),
                ('room_address', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=255, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('remove_time', models.DateTimeField(null=True)),
                ('datacenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_center.Datacenter')),
            ],
            options={
                'db_table': 'asset_room',
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_name', models.CharField(max_length=50)),
                ('rack_address', models.CharField(max_length=255, null=True)),
                ('remark', models.CharField(max_length=255, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('remove_time', models.DateTimeField(null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_center.Room')),
            ],
            options={
                'db_table': 'asset_rack',
            },
        ),
    ]
