# Generated by Django 3.0.6 on 2020-06-22 03:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('main_products', models.CharField(max_length=255, null=True)),
                ('sign_up_time', models.CharField(max_length=50, null=True)),
                ('enterprise_type', models.CharField(max_length=50, null=True)),
                ('remark', models.TextField(null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('remove_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'asset_vendor',
            },
        )
    ]
