# Generated by Django 3.0.6 on 2020-06-22 03:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic_resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=60)),
                ('sign_time', models.CharField(max_length=50, null=True)),
                ('remark', models.TextField(null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('remove_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'asset_contract',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别')),
                ('remark', models.TextField(null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('remove_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'asset_staff',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('remark', models.TextField(null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('remove_time', models.DateTimeField(null=True)),
                ('staff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logic_resource.Staff')),
            ],
            options={
                'db_table': 'asset_business',
            },
        ),
    ]
