# Generated by Django 3.0.5 on 2020-04-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic_resource', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='room',
            new_name='staff',
        ),
    ]
